#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import C kivy.utils.get_color_from_hex
#:import Color kivy.graphics.Color
#:import clip kivy.core.clipboard.Clipboard
<Meet_Lobby>:
    transition: NoTransition()

    Screen:
        name : 'meet_lobby'
        FloatLayout:
            Image:
                id: image_background_
                allow_stretch: True
                height: root.height
                width: root.width
                keep_ratio: False
                size: self.texture_size
                source : ''
            BoxLayout:
                orientation: 'vertical' 

                BoxLayout:
                    id : lobby_toolbar
                    size_hint_y: None
                    height: 50

                    canvas:
                        Color:
                            rgba: root.meet_link_canvas_color
                        Rectangle:
                            size: self.size
                            pos: self.pos
                        Color:
                            rgba: 1,1,1,1
                        Rectangle:
                            size: (400,1)
                            pos: self.pos


                    Label:
                        id : link_lab
                        color: root.lessons_text_color
                        text: root.to_arabic('   مكتبة الروابط   ')
                        font_name: 'arabic'
                        font_size: 25
                        text_size: self.size
                        halign: 'right'
                        valign: 'middle'
                    

                BoxLayout:
                    orientation: 'vertical'
                    id: main_lobby
                    

                    ScrollView:
                        color: 0,0,0,0

                        BoxLayout:
                            id: lessons_table
                            orientation: 'vertical'
                            size_hint_y: None
                            height: 150

                    

                            

                BoxLayout:
                    id: add_or_del
                    size_hint_y: None
                    height: 40
                    orientation: 'vertical'

                    BoxLayout:
                        spacing: 5
                        padding: [5,0,5,0]

                        ImageButton:
                            id : first_button
                            source: 'tex/setting_button_normal.png'
                            allow_stretch:  True
                            size_hint: None, None
                            size: (40,40)
                            on_press: root.recover_setting()
                            on_press: root.current = 'setting_panel_name'

                        BoxLayout:
                            

                        Button:
                            id: editor_mode
                            text: root.to_arabic('تحرير')
                            font_name: 'arabic'
                            size_hint_x: None
                            on_release: root.editor()
                            width: 70
                            background_normal: 'tex/setting_icon_apply.png'
                            border: [5]*4
                            font_size: 18


                        Button:
                            text: root.to_arabic('أضافة دروس')
                            font_name: 'arabic'
                            on_press :root.current = 'meet_adder'
                            on_release: root.edit_mode = False
                            on_release: editor_mode.text = root.to_arabic('تحرير')
                            background_normal: ''
                            background_normal: 'tex/setting_icon_apply.png'
                            background_color: C('#3fade7ff')
                            size_hint_x: None
                            width: 90
                            border: [5]*4
                            font_size: 18
                            

                BoxLayout:
                    size_hint_y: None
                    height: 20

    Screen:
        name: 'setting_panel_name'

        BoxLayout:
            id : 'setting_panel'
            orientation: 'vertical'

            canvas.before:
                Color:
                    rgb: C('#242424ff')
                Rectangle:
                    size: self.size

                

            BoxLayout:
                size_hint_y: None
                height: 50
                canvas:
                    Color:
                        rgb: C('#373737ff')
                    Rectangle:
                        size: self.size
                        pos: self.pos
                Label:
                    font_size: 25
                    font_name: 'arabic'
                    text: root.to_arabic('ألاعدادات')
                    text_size: self.size
                    valign: 'center'
                    halign: 'center'

            
            BoxLayout:
                padding: 10
                Label:
                    font_size: 20
                    text: str(int(text_size_slider.value))
                    size_hint: None,1
                    width: 20
                      
                Slider:
                    id : text_size_slider
                    max : 30
                    min: 10
                    value : 20
                    cursor_image: 'tex/courser_normal.png'
                    cursor_size: [20,20]
                    
                Label:
                    text: root.to_arabic('حجم الخط')
                    font_name: 'arabic'
                    font_size: 20
                    size_hint_x: None
                    width: 80

            BoxLayout:
                padding: 10
                Label:
                    font_size: 20
                    text: str(text_trans_slider.value)[:3]
                    size_hint: None,1
                    width: 20
                      
                Slider:
                    id : text_trans_slider
                    max : 1
                    min: 0
                    value : 0.7
                    cursor_image: 'tex/courser_normal.png'
                    cursor_size: [20,20]
                    
                Label:
                    text: root.to_arabic('الشفافية')
                    font_name: 'arabic'
                    font_size: 20
                    size_hint_x: None
                    width: 80

            BoxLayout:
                orientation: 'vertical'
                padding: 5
                Button:
                    text: root.to_arabic('   تغير الخلفية...')
                    background_normal: 'tex/setting_icon_apply.png'
                    border: (10,)*4
                    font_name: 'arabic'
                    font_size: 20
                    pos_hint: {'right':1}
                    size_hint_x: None
                    width: 120
                    on_release: root.current = 'image_chooser'

            BoxLayout:
                orientation: 'vertical'

                BoxLayout:
                    BoxLayout:

                    CheckBox:
                        id: text_color
                        active: True
                        on_active: root.check_color_2()
                    Label:
                        text: root.to_arabic('  لون الخط')
                        font_name: 'arabic'
                        font_size: 20
                        size_hint_x: None
                        width: 80
                        halign: 'right'
                        
                BoxLayout:
                    BoxLayout:

                    CheckBox:
                        id: canvas_color
                        on_active: root.check_color_2()

                    Label:
                        text: root.to_arabic('  لون القالب')
                        font_name: 'arabic'
                        font_size: 20
                        size_hint_x: None
                        width: 80
                        halign: 'right'

            BoxLayout:

                Slider:
                    id : color_slider_h        
                    max : 1
                    min: 0
                    value : 0
                    cursor_image: 'tex/courser_normal.png'
                    cursor_size: [20,20]

                Label:
                    text: 'H'
                    size_hint_x: None
                    width: 40
            BoxLayout:

                Slider:
                    id : color_slider_s
                    max : 1
                    min: 0
                    value : 0
                    cursor_image: 'tex/courser_normal.png'
                    cursor_size: [20,20]
                Label:
                    text: 'S'   
                    size_hint_x: None
                    width: 40
            BoxLayout:

                Slider:
                    id : color_slider_v
                    max : 1
                    min: 0
                    value : 1
                    cursor_image: 'tex/courser_normal.png'
                    cursor_size: [20,20]
                Label:
                    text: 'V'   
                    size_hint_x: None
                    width: 40

            FloatLayout:
                id : image_box
                orientation: 'vertical'
                size_hint_y: None
                height: 150
                BoxLayout:
                    size_hint_y: None
                    height: 0
                    pos_hint: {'y':0.28}
                    BoxLayout:
                        id: thumb_container
                        BoxLayout:
                            canvas:
                                Rectangle:
                                    source: root.thumb_image
                                    pos: 0, image_box.pos[1] + 37
                                    size: root.width, 70
                    BoxLayout:
                        canvas:
                            Color:
                                rgba: tuple(Color(color_slider_h.value, color_slider_s.value, color_slider_v.value, text_trans_slider.value ,mode='hsv').rgba) if canvas_color.active else [root.canvascolor[0],root.canvascolor[1],root.canvascolor[2],text_trans_slider.value]
                            Line:
                                points: 20,30+image_box.pos[1]+40,    20,30+image_box.pos[1]+50,     root.width-20,30+image_box.pos[1]+50,    root.width-20,30+image_box.pos[1]+40
                                close: True
                                width: 14

                BoxLayout:
                    pos_hint: {'y':0.01}
                    R_Button_change:
                        color: 1,0,0
                        id: display_time
                        text: root.to_arabic("03:00م - 12:00ص")
                        font_size: text_size_slider.value
                        color: tuple(Color(color_slider_h.value, color_slider_s.value, color_slider_v.value, mode='hsv').rgba) if text_color.active else root.textcolor
                    R_Button_change:
                        id: display_name
                        text: root.to_arabic("برمجة")
                        font_size: text_size_slider.value
                        color: tuple(Color(color_slider_h.value, color_slider_s.value, color_slider_v.value, mode='hsv').rgba) if text_color.active else root.textcolor


                    

                
            BoxLayout:
                
                

            BoxLayout:
                padding: 5
                spacing: 5
                AR_Button:
                    text: root.to_arabic('الاعدات الافتراضية')
                    on_press: root.dev_setting()
                    on_press: root.current = 'meet_lobby'
                    background_normal: 'tex/setting_icon_back.png'
                    width: 130

                BoxLayout:
                    
                AR_Button:
                    text: root.to_arabic('الغاء')
                    on_release: root.current = 'meet_lobby'
                    on_release: root.cancel_new_setting()
                    background_normal: 'tex/setting_icon_cansal.png'
                    color: C('#373737ff')
                    width: 46

                AR_Button:
                    text: root.to_arabic('تطيبق')
                    on_press: root.apply_new_setting()
                    on_press: root.current = 'meet_lobby'
                    background_normal: 'tex/setting_icon_apply.png'
                    width: 60

                    

            BoxLayout:



    Screen:
        name: 'image_chooser'

        FloatLayout:
            id : first_float
            canvas.before:
                Color:
                    rgb: C('#242424ff')
                Rectangle:
                    size: self.size
                    pos: self.pos
            BoxLayout:
                canvas:
                    Color:
                        rgba: 1,1,1,0.2
                    Rectangle:
                        pos: root.width/4 + root.width*0.05, root.height/2 + root.height*0.05
                        size: root.width * 0.4, root.height* 0.4
            Scatter:
                id: image_scatter
                auto_bring_to_front: False
                do_rotation: False

                Image:
                    id: image_in_scatter
                    source: root.current_background if root.not_select_yet else root.sel_image

                    pos:  root.width/2 - image_in_scatter.size[0]/2 , root.height*0.75 - image_in_scatter.size[1]/2 
                    size: self.texture_size[0]*0.4, self.texture_size[1]*0.4
            BoxLayout:
                canvas:
                    Color:
                        rgba: 1,1,1,0.7
                    Line:
                        points: root.width/4 + root.width*0.05,root.height/2 + root.height*0.05  ,   root.width/4 + root.width*0.05,root.height/2 + root.height*0.05+root.height* 0.4    ,    root.width/4 + root.width*0.05+root.width * 0.4,root.height/2 + root.height*0.05+root.height* 0.4  ,root.width/4 + root.width*0.05+root.width * 0.4, root.height/2 + root.height*0.05 
                        close: True
                        
            Button:
                text: root.to_arabic('الغاء')
                size_hint: None, None
                size: 90, 30
                pos_hint: {'x':0.05,'y':0.53}
                font_name: 'arabic'
                background_normal:'tex/setting_icon_cansal.png'
                background_color: C('#3fade7ff')
                border:[5]*4
                font_size:20
                on_release: root.current = 'setting_panel_name'



            Button:
                text: root.to_arabic('تطبيق')
                font_name: 'arabic'
                size_hint: None, None
                size: 90, 30
                pos_hint: {'right':0.95,'y':0.53}
                background_normal: ''
                background_normal: 'tex/setting_icon_apply.png'
                background_color: C('#3fade7ff')
                border: [5]*4
                font_size: 20
                on_release: root.apply_new_background()

            BoxLayout:
                size_hint: None, None
                width: root.width
                height: root.height/2
                canvas.before:
                    Color:
                        rgb: C('#373737ff')
                    Rectangle:
                        size: self.size
                        pos: self.pos

                FileChooserListView:
                    id: filetchooser
                    on_selection: root.select_image(filetchooser.selection)

                    on_selection: image_scatter.pos = (0,0)
                    on_selection: image_scatter.size = (1,1)
            
            
        






                
                

        
    
    Screen:
        name: 'welcome'
        BoxLayout:
            orientation:'vertical'



            

    Screen:
        name: 'meet_adder'
        BoxLayout:
            id : meet_add_main
            orientation: 'vertical'
            width: root.width

            canvas:
                Color:
                    rgba: C('#242424ff')
                Rectangle:
                    size: self.size
                    pos: self.pos

            BoxLayout:
                id: topbar
                size_hint: None, None
                height: 50
                width: meet_add_main.width
                pos: 0, 300
                padding: 5
                canvas:
                    Color:
                        rgba: C('#373737ff')
                    Rectangle:
                        size: self.size
                        pos: self.pos

                Button:
                    size: 40,40
                    size_hint: None, None
                    background_normal: r'tex\meet_add_back_arrow.png'
                    background_down: r'tex\meet_add_back_arrow_down.png'
                    border: (0,0,0,0)
                    pos_hint: {'center_y':0.5}
                    on_release: root.current= 'meet_lobby'
                    on_release: root.edit_mode = False
                    on_release: root.clean_list()
                    on_release: editor_mode.text = root.to_arabic('تحرير')
                    on_release: root.clean_text()

                Label:
                    text: root.to_arabic('   أضافة درس')
                    font_name: 'arabic'
                    font_size: 22
                    text_size: self.texture_size
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'

            BoxLayout:
                id : mat_type 
                width: root.width
                orientation: 'vertical'
                size_hint_y: None
                height: 150
                padding: 10
                spacing: 10
                BoxLayout:
                    size_hint_y: None
                    height: 20
                    orientation: 'vertical'
                    Label:
                        pos_hint: {'center_y':0.5}
                        text: root.to_arabic('أسم المادة')
                        color: 1,1,1
                        font_name: 'arabic'
                        font_size: 20
                Ar_text:
                    text: ''
                    id: mat_name
                    size_hint_y: None
                    height: 30
                    text_size: self.size
                    halign: 'right'
                    foreground_color: 1,1,1
                    background_normal: r'tex\text_nor.png'
                    background_active: r'tex\text_down.png'
                    hint_text : root.to_arabic('الرسم الهندسي')
                
                BoxLayout:
                    size_hint_y: None
                    height: 20
                    orientation: 'vertical'
            
                    Label:
                        pos_hint: {'center_y':0.5}
                        text: root.to_arabic('الرابط')
                        color: 1,1,1
                        font_name: 'arabic'
                        font_size: 20
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 5
                    TextInput:
                        text: ''
                        id: link
                        size_hint_y: None
                        height: 30
                        multiline: False
                        foreground_color : 1,1,1
                        background_normal: r'tex\text_nor.png'
                        background_active: r'tex\text_down.png'
                        hint_text: r'www.meet.goolge.com\xxx-xxxx-xxx'
                    Button:
                        text: root.to_arabic('لصق')
                        font_name: 'arabic'
                        size_hint: None, None
                        height: 30
                        width: 60
                        border: 10,10,10,10
                        pos_hint: {'center_y':0.5}
                        on_release: link.text = clip.paste()
                        background_normal: r'tex\setting_icon_apply.png'
                        background_down: r'tex\setting_icon_cansal.png'


            BoxLayout:
                

            BoxLayout:
                padding: 10
                spacing: 10
                pos_hint: {'center_y':0.5}
                size_hint: None, None
                width: root.width
                orientation: 'vertical'
                id : calen
                height: 200


                BoxLayout:
                    size_hint: None, None
                    height: calen.height/6
                    width: calen.width-20


                    Button:
                        id: to_sonday
                        background_color: [1,1,1,0]
                        background_normal: ''
                        size_hint_y: None
                        height: 30
                        pos_hint: {'center_y':0.5}
                        font_size: root.calender_font_size
                        color: 0.6,0.6,0.6
                        text: '00:00'
                        on_release: root.whose_sent_time('to_sonday'), root.show_time_picker()

                    Label:
                        id: to_sonday_label
                        text: root.to_arabic('آلى')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                        color: 0.6,0.6,0.6
                    time_button:
                        id: from_sonday
                        text: '00:00'
                        on_release: root.whose_sent_time('from_sonday'), root.show_time_picker()
                        font_size: root.calender_font_size
                        color :0.6,0.6,0.6
                    Label:
                        color: 0.6,0.6,0.6
                        id: from_sonday_label
                        text: root.to_arabic('من')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    Label:
                        color: 0.6,0.6,0.6
                        id: sonday
                        text: root.to_arabic('ألاحد')
                        font_name: 'arabic'
                        font_size: root.calender_font_size                        
                
                    CheckBox:
                        id: check_day_1
                        on_active: root.color_check('sonday')
                        background_checkbox_normal: 'tex/checkbox_normal.png'
                        background_checkbox_down: 'tex/checkbox_down.png'
                    
                        


                BoxLayout:
                    size_hint: None, None
                    height: calen.height/6
                    width: calen.width-20

                    canvas.after:
                        Color:
                            rgba: 0,0,0,.3
                        Rectangle:
                            pos: self.pos
                            size: calen.width-20,1

                    Button:
                        id: to_monday
                        background_color: [1,1,1,0]
                        background_normal: ''
                        size_hint_y: None
                        height: 30
                        pos_hint: {'center_y':0.5}
                        color: 0.6,0.6,0.6
                        font_size: root.calender_font_size
                        text: '00:00'
                        on_release: root.whose_sent_time('to_monday'), root.show_time_picker()

                    Label:
                        color: 0.6,0.6,0.6
                        id: to_monday_label
                        text: root.to_arabic('آلى')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    time_button:
                        id: from_monday
                        text: '00:00'
                        on_release: root.whose_sent_time('from_monday'), root.show_time_picker()
                        font_size: root.calender_font_size

                    Label:
                        color: 0.6,0.6,0.6
                        id: from_monday_label
                        text: root.to_arabic('من')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    Label:
                        color: 0.6,0.6,0.6
                        id: monday
                        text: root.to_arabic('الاثنين')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    CheckBox:
                        id: check_day_2
                        on_active: root.color_check('monday')
                        background_checkbox_normal: 'tex/checkbox_normal.png'
                        background_checkbox_down: 'tex/checkbox_down.png'
                        
                BoxLayout:
                    size_hint: None, None
                    height: calen.height/6
                    width: calen.width-20

                    canvas.after:
                        Color:
                            rgba: 0,0,0,.3
                        Rectangle:
                            pos: self.pos
                            size: calen.width-20,1

                    Button:
                        id: to_tuesday
                        background_color: [1,1,1,0]
                        background_normal: ''
                        size_hint_y: None
                        height: 30
                        pos_hint: {'center_y':0.5}
                        color: 0.6,0.6,0.6
                        font_size: root.calender_font_size
                        text: '00:00'
                        on_release: root.whose_sent_time('to_tuesday'), root.show_time_picker()

                    Label:
                        color: 0.6,0.6,0.6
                        id: to_tuesday_label
                        text: root.to_arabic('آلى')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    time_button:
                        id: from_tuesday
                        text: '00:00'
                        on_release: root.whose_sent_time('from_tuesday'), root.show_time_picker()
                        font_size: root.calender_font_size

                    Label:
                        color: 0.6,0.6,0.6
                        id: from_tuesday_label
                        text: root.to_arabic('من')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    Label:
                        color: 0.6,0.6,0.6
                        id: tuesday
                        text: root.to_arabic('الثلاثاء')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    CheckBox:
                        id: check_day_3
                        on_active: root.color_check('tuesday')
                        background_checkbox_normal: 'tex/checkbox_normal.png'
                        background_checkbox_down: 'tex/checkbox_down.png'

                BoxLayout:
                    size_hint: None, None
                    height: calen.height/6
                    width: calen.width-20

                    canvas.after:
                        Color:
                            rgba: 0,0,0,.3
                        Rectangle:
                            pos: self.pos
                            size: calen.width-20,1

                    Button:
                        id: to_wednesday
                        background_color: [1,1,1,0]
                        background_normal: ''
                        size_hint_y: None
                        height: 30
                        pos_hint: {'center_y':0.5}
                        color: 0.6,0.6,0.6
                        font_size: root.calender_font_size
                        text: '00:00'
                        on_release: root.whose_sent_time('to_wednesday'), root.show_time_picker()

                    Label:
                        color: 0.6,0.6,0.6
                        id: to_wednesday_label
                        text: root.to_arabic('آلى')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    time_button:
                        id: from_wednesday
                        text: '00:00'
                        on_release: root.whose_sent_time('from_wednesday'), root.show_time_picker()
                        font_size: root.calender_font_size

                    Label:
                        color: 0.6,0.6,0.6
                        id: from_wednesday_label
                        text: root.to_arabic('من')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    Label:
                        color: 0.6,0.6,0.6
                        id: wednesday
                        text: root.to_arabic('الاربعاء')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    CheckBox:
                        id: check_day_4
                        on_active: root.color_check('wednesday')
                        background_checkbox_normal: 'tex/checkbox_normal.png'
                        background_checkbox_down: 'tex/checkbox_down.png'


                BoxLayout:
                    size_hint: None, None
                    height: calen.height/6
                    width: calen.width-20

                    canvas.after:
                        Color:
                            rgba: 0,0,0,.3
                        Rectangle:
                            pos: self.pos
                            size: calen.width-20,1

                    Button:
                        id: to_thursday
                        background_color: [1,1,1,0]
                        background_normal: ''
                        size_hint_y: None
                        height: 30
                        pos_hint: {'center_y':0.5}
                        color: 0.6,0.6,0.6
                        font_size: root.calender_font_size
                        text: '00:00'
                        on_release: root.whose_sent_time('to_thursday'), root.show_time_picker()

                    Label:
                        color: 0.6,0.6,0.6
                        id: to_thursday_label
                        text: root.to_arabic('آلى')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    time_button:
                        id: from_thursday
                        text: '00:00'
                        on_release: root.whose_sent_time('from_thursday'), root.show_time_picker()
                        font_size: root.calender_font_size

                    Label:
                        color: 0.6,0.6,0.6
                        id: from_thursday_label
                        text: root.to_arabic('من')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    Label:
                        color: 0.6,0.6,0.6
                        id: thursday
                        text: root.to_arabic('الخميس')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    CheckBox:
                        id: check_day_5
                        on_active: root.color_check('thursday')
                        background_checkbox_normal: 'tex/checkbox_normal.png'
                        background_checkbox_down: 'tex/checkbox_down.png'


                BoxLayout:
                    size_hint: None, None
                    height: calen.height/6
                    width: calen.width-20

                    Button:
                        id: to_saturday
                        background_color: [1,1,1,0]
                        background_normal: ''
                        size_hint_y: None
                        height: 30
                        pos_hint: {'center_y':0.5}
                        color: 0.6,0.6,0.6
                        font_size: root.calender_font_size
                        text: '00:00'
                        on_release: root.whose_sent_time('to_saturday'), root.show_time_picker()

                    Label:
                        color: 0.6,0.6,0.6
                        id: to_saturday_label
                        text: root.to_arabic('آلى')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    time_button:
                        id: from_saturday
                        text: '00:00'
                        on_release: root.whose_sent_time('from_saturday'), root.show_time_picker()
                        font_size: root.calender_font_size

                    Label:
                        color: 0.6,0.6,0.6
                        id: from_saturday_label
                        text: root.to_arabic('من')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    Label:
                        color: 0.6,0.6,0.6
                        id: saturday
                        text: root.to_arabic('السبت')
                        font_name: 'arabic'
                        font_size: root.calender_font_size
                    CheckBox:
                        id: check_day_6
                        on_active: root.color_check('saturday')
                        background_checkbox_normal: 'tex/checkbox_normal.png'
                        background_checkbox_down: 'tex/checkbox_down.png'

            BoxLayout:
                       
            BoxLayout:
                orientation: 'horizontal'
                id : adder_last_panel
                size: root.width, 40
                size_hint_y: None 
                padding: 10
                spacing: 10
                
                BoxLayout:
                    
                AR_Button:
                    text: root.to_arabic('مسح')
                    background_normal: 'tex/setting_icon_apply.png'
                    on_release: root.current = 'meet_lobby'
                    on_release: root.class_del()
                    on_release: root.edit_mode = False
                    on_release: editor_mode.text = root.to_arabic('تحرير')

                AR_Button:
                    text: root.to_arabic('أنشاء')
                    on_release: root.make_new_lesson()

                    background_normal: ''
                    background_normal: 'tex/setting_icon_apply.png'
                    background_color: C('#3fade7ff')
                    


                
                    
        
                    
            BoxLayout:
                size_hint_y: None
                height: 20



    



<time_button@Button>:
    text: 'ddd'
    background_color: [1,1,1,0]
    background_normal: ''
    size_hint_y: None
    height: 30
    pos_hint: {'center_y':0.5}
    color: 0.6,0.6,0.6   
<AR_Button@Button>:
    font_name: 'arabic'
    font_size: 20
    border: (5,)*4
    size_hint: None, None
    height: 30
<R_Button_change@Button>:
    background_normal: ''
    background_donw: ''
    text_size: self.size
    halign: 'center'
    valign: 'center'
    background_color: 0,0,0,0
    font_name: 'arabic'

<BackgroundColor@Widget>
    background_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos

<ImageButton@ButtonBehavior+Image>:
    padding: [2, 2, 2, 2]




            
<test_size@canvas>:
    Color:
        rgba: 1,1,0,1
    Rectangle:
        size: self.size
        pos: self.size

<Ar_text@TextInput>:
    text: ""
    multiline: 0
    #size_hint: 1,1
    font_name: 'arabic'
    font_size: 20
    #padding_y: [15,0] # can be changed
    #padding_x: [self.size[0]-self._get_text_width(max(self._lines, key=len), self.tab_width, self._label_cached)-10,8]
